# pdb_code chain
./extract_chain.sh 1a0f A
./extract_chain.sh 1a7v A
./extract_chain.sh 1ba3 A
./extract_chain.sh 1bfm A
./extract_chain.sh 1bnl A
./extract_chain.sh 1d5g A
./extract_chain.sh 1div A
./extract_chain.sh 1dxx A
./extract_chain.sh 1ekg A
./extract_chain.sh 1f8i A
./extract_chain.sh 1fh5 H
./extract_chain.sh 1frd A
./extract_chain.sh 1ft8 A
./extract_chain.sh 1fxa A
./extract_chain.sh 1g3p A
./extract_chain.sh 1glu A
./extract_chain.sh 1gua B
./extract_chain.sh 1gwy A
./extract_chain.sh 1h0x A
./extract_chain.sh 1hcq A
./extract_chain.sh 1ioj A
./extract_chain.sh 1ir3 A
./extract_chain.sh 1itm A
./extract_chain.sh 1iv7 B
./extract_chain.sh 1iv9 A
./extract_chain.sh 1j8i A
./extract_chain.sh 1jl9 A
./extract_chain.sh 1jlv A
./extract_chain.sh 1l6h A
./extract_chain.sh 1lvm A
./extract_chain.sh 1n18 A
./extract_chain.sh 1n88 A
./extract_chain.sh 1nm1 A
./extract_chain.sh 1o1u A
./extract_chain.sh 1o6x A
./extract_chain.sh 1osi A
./extract_chain.sh 1pfl A
./extract_chain.sh 1pre A
./extract_chain.sh 1prg A
./extract_chain.sh 1r2y A
./extract_chain.sh 1r6r A
./extract_chain.sh 1spd A
./extract_chain.sh 1x0j A
./extract_chain.sh 1xws A
./extract_chain.sh 1xxn A
./extract_chain.sh 1xzo A
./extract_chain.sh 2arf A
./extract_chain.sh 2bjd A
./extract_chain.sh 2c9q A
./extract_chain.sh 2clr B
./extract_chain.sh 2dvv A
./extract_chain.sh 2h3f A
./extract_chain.sh 2hbb A
./extract_chain.sh 2jie A
./extract_chain.sh 2juc A
./extract_chain.sh 2kj3 A
./extract_chain.sh 2ks4 A
./extract_chain.sh 2ltb A
./extract_chain.sh 2m5s A
./extract_chain.sh 2mpc A
./extract_chain.sh 2n7z A
./extract_chain.sh 2nte A
./extract_chain.sh 2ouo A
./extract_chain.sh 2pr5 A
./extract_chain.sh 2ptl A
./extract_chain.sh 2rpn A
./extract_chain.sh 2vy0 A
./extract_chain.sh 2wqg A
./extract_chain.sh 2zta A
./extract_chain.sh 3bci A
./extract_chain.sh 3bn0 A
./extract_chain.sh 3c2i A
./extract_chain.sh 3d2a A
./extract_chain.sh 3d3b A
./extract_chain.sh 3dv0 I
./extract_chain.sh 3ecu A
./extract_chain.sh 3fis A
./extract_chain.sh 3g1g A
./extract_chain.sh 3k82 A
./extract_chain.sh 3l15 B
./extract_chain.sh 3mon B
./extract_chain.sh 3o39 A
./extract_chain.sh 3s4m A
./extract_chain.sh 3s92 A
./extract_chain.sh 4bjx A
./extract_chain.sh 4buq A
./extract_chain.sh 4he7 A
./extract_chain.sh 4n6v 0
./extract_chain.sh 4waa A
./extract_chain.sh 4yee A
./extract_chain.sh 4yef A
./extract_chain.sh 5jxb A
./extract_chain.sh 5oaq A
./extract_chain.sh 5vp3 A
